### ISSUE TITLE
support `HPCC_MSVC_MD`

### ISSUE THREAD

**Issue by lzhangzz** [openppl-public/hpcc#4]
The removal of `HPCC_MSVC_MD`  in 266579679761dd2c37440c700fb5602187056fce forces downstream libraries to also use static MSVC runtime, which is unsafe when multiple DLLs are interoperating. 

Can we bring back this feature?

**Comment by ouonline** [comment]
you can use `PPLNN_USE_MSVC_STATIC_RUNTIME` for ppl.nn and `PPLCV_USE_MSVC_STATIC_RUNTIME` for ppl.cv to choose the msvc runtime.
